export { default as WebNav } from './WebNav/WebNav'
export { default as HomeSec } from './HomeSec/HomeSec'
export { default as ServicesSec } from './ServicesSec/ServicesSec'
export { default as CategorySec } from './CategorySec/CategorySec'
export { default as ContactSec } from './ContactSec/ContactSec'
export { default as ProfileHeader } from './ProfileHeader/ProfileHeader'
export { default as Favourites } from './Favourites/Favourites'
export { default as Footer } from './Footer/Footer'
